kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: "{{ .Values.storage }}-claim"
    annotations:
        volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 40G
